version: '3'
networks:
  app-network:
    driver: bridge

volumes:
  node_modules:

services:
  nodejs:
    build:
      context: .
      dockerfile: DockerfileNode
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network