version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: bot/DockerNode
    container_name: nodejs
    restart: unless-stopped
    env_file: bot/.env
    ports:
      - "3000:80"

  nginx:
    build:
      context: .
      dockerfile: nginx/DockerNginx
    container_name: walking_suit
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"