version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: bot/DockerNode
    container_name: nodejs
    restart: unless-stopped
    env_file: bot/.env
    ports:
      - "3000:3000"
    networks:
      - nginx-net

  nginx:
    build:
      context: .
      dockerfile: nginx/DockerNginx
    container_name: walking_suit
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true